### PR TITLE
Create new date-time package with DatePicker

### PR DESCRIPTION
**Pull request by jamesricky**
Story: https://deploy-preview-574--comet-admin.netlify.app/?path=/story/comet-admin-date-time--date-picker

---

Created a new date-time package to contain all date and time related components, for use in forms, such as DatePicker, DateRangePicker, TimePicker, DateTimePicker.

Implemented the DatePicker and FinalFormDatePicker, for now, using the default styling, provided by 'react-date-range' and without allowing text-input by the user.

Created the InputWithPopper component in the admin package to use as a base for the DatePicker and other future pickers.
 It renders the input and handles the opening and closing logic of the popper, preventing inconsistencies in the behaviour of the different picker components.

### CODE REVIEW

**Comment by dkarnutsch** [comment]
This picker is currently not usable with a keyboard (= setting 01.01.1950 using the keyboard). Is this something we need / want?

**Comment by jamesricky** [comment]
> This picker is currently not usable with a keyboard (= setting 01.01.1950 using the keyboard). Is this something we need / want?

As we discussed in our meeting, the initial implementation will be without text-input, to allow for a fast replacement of the old package. 

Parsing, validating with the correct locale and rendering errors without direct access to the `Field`'s error-prop is a bit difficult and time intensive. 

https://vivid-planet.atlassian.net/wiki/spaces/COM/pages/91586569/2022-02-23+comet-admin+JFX+Sprint+8
> Initialer Ersatz: Wir machen jeweils einen Date-Picker und Date-Range-Picker, ohne Text-Input. 
> Wäre relativ einfach/schnell umgesetzt.

**Comment by dkarnutsch** [comment]
Alright 👍

**Review by dkarnutsch — APPROVED** [review]

**Review by thomasdax98 — APPROVED** [review]

**Review by nsams — APPROVED** [review]

**Review by johnnyomair — APPROVED** [review]
I really like how you separated `DatePicker` and `FinalFormDatePicker` 👍🏼

**Comment by johnnyomair** [comment]
The style of the calendar doesn't seem to be in line with our Comet theme. Do you plan to change that in a future PR?

**Comment by jamesricky** [comment]
> The style of the calendar doesn't seem to be in line with our Comet theme. Do you plan to change that in a future PR?

Yes, that's a future PR 🙂

**Pull request merged**
