### PR TITLE
Replace custom InputBase with InputBase from material-ui

### PR DESCRIPTION
**Pull request by jamesricky**
This simplifies usage of the InputBase which now always has the comet-styling.
Previously, the comet-styling would often not be set because the wrong component would be used.

As a result some previously hidden type-errors needed to be fixed:

- Fix type-errors from hex-input change-event
- Value of InputBase placeholder must be a string

**This was previously #439**

### CODE REVIEW

**Comment by jamesricky** [comment]
Comment from @nsams in #439:

> I think that breaks TextField, question is if we consider that a problem.
>
> Let me explain:
> 
> - from mui docs: "The TextField wrapper component is a complete form control including a label, input and help text."
> - and "TextField is composed of smaller components ( FormControl, Input, FilledInput, InputLabel, OutlinedInput, and FormHelperText )"
> - we usually don't use this TextField component, as we don't need the material design way of rendering label etc
> - we usually use just Input in our forms and render label, error etc ourself
> - when we style the mui Input (or indirectly thru InputBase) for our usage of Input, we potentially break it for TextField usage
> 
> now the big question is: is that a problem? Do we care if TextField is broken?

**Comment by jamesricky** [comment]
> I think that breaks TextField, question is if we consider that a problem.

@nsams yes, this does break the styling of the Mui-TextField. 

I don't think this is a problem, because the MuiTextField is not Comet-CI conform and should therefore not be used anyway. 

For TextFields outside of a FinalForm we should always use our FieldContainer in combination with MuiInputBase, which achieves a similar result and is Comet-CI conform: 
```tsx
<FieldContainer label="Input Label">
    <InputBase onChange={handleChange} value={value} />
</FieldContainer>
```

_If there ever is a project where the label-behaviour and styling of MuiTextField is required we probably want to remove the comet-theme anyway, which would fix the problem. Alternatively we can always fix/remove the styling of the InputBase inside MuiTextField if this is every necessary._

**Comment by rabengraph** [comment]
> I think that breaks TextField, question is if we consider that a problem.


I do not understand how relevant this is.
As already have been said, we never use TextField because it does way to much for comet-purposes (label + helper text).
Why did we use TextField for 'search-autocomplete' in the first place, BaseInput does all what 'search-autocomplete' needs.

**Comment by nsams** [comment]
> Why did we use TextField for 'search-autocomplete' in the first place, BaseInput does all what 'search-autocomplete' needs.

100% correct.

But devs are sometimes still using TextField (search-autocomplete story or packages/admin-rte/src/core/extension/Link/ToolbarButton.tsx)

I guess because of mui docs and other code examples found on the internet. (after all we tell peope that comet-admin is standard mui)

Now the question is:

- should we somehow (programatically? docs?) better avoid the usage of TextField (and don't care if TextField is broken)
- allow usage of TextField but not recommend it (and don't break it)

BTW: we even have FinalFormTextField in comet-admin (could be removed, it already confused people)

**Comment by rabengraph** [comment]
> BTW: we even have FinalFormTextField in comet-admin (could be removed, it already confused people)

I think /admin/src/form/TextField.tsx should be removed, this wrapper has no real value, FinalFormInput is the Component to be use instead.

> I guess because of mui docs and other code examples found on the internet. (after all we tell peope that comet-admin is standard mui)

This is true. Comet-Admin is standard-mui, except for forms. This is general pain-point and leads to confusion.

**Comment by nsams** [comment]
We discussed this and came to the conclusion that:

- we don't want to support TextField with comet-admin
- this can be merged as it is
- FinalFormTextField has to be removed
- the two usages of TextField in comet-admin have to be adapted
- we will add a eslint rule that disallows TextField
- we have to <s>improve</s> write form docs

**Review by nsams — APPROVED** [review]

**Review by rabengraph — APPROVED** [review]

**Pull request merged**
