### PR TITLE
fix: generate global class names like mui does for comet components

### PR DESCRIPTION
**Pull request by kaufmo**
it is possible now to style nested components with cssSelector

### CODE REVIEW

**Review by manuelblum — APPROVED** [review]
lgtm

why don't we use the createGenerateClassName from @material-ui/core/styles which is shown in the examples?

Now we are using a kind like private api?

**Comment by manuelblum** [comment]
why don't we use the createGenerateClassName from @material-ui/core/styles which is shown in the examples?

Now we are using a kind like private api?

**Comment by kaufmo** [comment]
> why don't we use the createGenerateClassName from @material-ui/core/styles which is shown in the examples? https://material-ui.com/styles/api/#examples
> 
> Now we are using a kind like private api?

the private api is only used for styles with name prefix "Comet", rest of all styles uses the createGenerateClassName function from material ui styles ;)

**Review by jamesricky — APPROVED** [review]

**Comment by manuelblum** [comment]
setting the productionPrefix to CometAdmin wouldn't work either?

**Comment by kaufmo** [comment]
> setting the productionPrefix to CometAdmin wouldn't work either?

nope thats a different feature has nothing todo with this change

**Review by nsams — APPROVED** [review]

**Comment by nsams** [comment]
>why don't we use the createGenerateClassName from @material-ui/core/styles which is shown in the examples? https://material-ui.com/styles/api/#examples
>
> Now we are using a kind like private api?

I thought the same. And the require should be changed to import

**Comment by kaufmo** [comment]
> > why don't we use the createGenerateClassName from @material-ui/core/styles which is shown in the examples? https://material-ui.com/styles/api/#examples
> > Now we are using a kind like private api?
> 
> I thought the same. And the require should be changed to import

there are no types defined for nested, so what should I use ts-ignore with import or only require?

**Review by rabengraph — APPROVED** [review]

**Comment by kaufmo** [comment]
replaced now require with import :+1:

**Pull request merged**
