### PR TITLE
Add prop to render FormSection without Typography

### PR DESCRIPTION
**Pull request by jamesricky**
Previously, only when passing a string into the `title` prop,
the title would be wrapped by a Typography.

The thought behind this, was that a generic style would be added to the
title-text by default and when a custom component (e.g. Typography) was
needed that could simply be passed into the `title` prop and the
generic Typography would not be rendered.

The issue with this method was, that when passing in a component that
simply returned a text (e.g. FormattedMessage), the title would not
have the generic style because the type was not a string.

### CODE REVIEW

**Comment by nsams** [comment]
alternative idea; renderTitle prop with default value `(title) => <Typography>{title}</Typography>`? Or is that too difficult to override. How often do you have to override it?

**Comment by jamesricky** [comment]
> alternative idea; renderTitle prop with default value `(title) => <Typography>{title}</Typography>`? Or is that too difficult to override.

The reason I used a separate prop, was to stay consistent with material-ui: https://mui.com/api/list-item-text/#props

<br/>

> How often do you have to override it?

I don't think we use it very often, if at all 🤔

**Comment by jamesricky** [comment]
> alternative idea; renderTitle prop with default value `(title) => <Typography>{title}</Typography>`? Or is that too difficult to override. How often do you have to override it?

Also I don't want to write a function every time I set a title:
`<FormSection title={'MyTitle'}>` vs `<FormSection title={() => 'MyTitle'} />`

And allowing `React.Node` and `() => React.Node` adds too much complexity imo...

**Review by nsams — APPROVED** [review]
> The reason I used a separate prop, was to stay consistent with material-ui: https://mui.com/api/list-item-text/#props

that is a very good reason :)

**Review by johnnyomair — APPROVED** [review]

**Pull request merged**
