### PR TITLE
Set fixed dialog width and add generic buttons

### PR DESCRIPTION
**Pull request by jamesricky**
Depends on #426 

- Define values for multiple size-variants of the Dialog, controlled over the `maxWidth` and `fullWidth` props (all the variants can be tested by changing the select "Choose dialog size" in the story)
- `RouterConfirmationDialog` is an exception, because it might appear above another dialog
- In addition to the existing `SaveButton`, generic "cancel" and "okay" buttons should bring more consistency

### CODE REVIEW

**Comment by nsams** [comment]
what if the dialog content is larget than the set size?

**Comment by jamesricky** [comment]
> what if the dialog content is larget than the set size?

In the comet-design that should never be the case.  
If this is required for another design, you can customize that theme or the individual component or use the `fullWidth` prop on the `Dialog`.

**Comment by nsams** [comment]
You can never know what an application puts into an Dialog, that can be complex and large.

wouldn't something like a min-size be a solution?

**Comment by jamesricky** [comment]
@nsams I think this is a better solution now. Depending on the use-case you can define a specific size-variant by changing the `maxWidth` and `fullWidth` props, as intended by material-ui. The default value is `maxWidth="sm"` which then has a width of 600.

**Comment by nsams** [comment]
do I understand this correctly: you are basically using an existing mui feature?

**Comment by nsams** [comment]
the story is very complicated :)

I would prefer using knobs for changing the maxWidth, that would be so much simpler. (usable only for dev-story tough)

**Comment by jamesricky** [comment]
> do I understand this correctly: you are basically using an existing mui feature?

Yes 👍🏻

**Comment by jamesricky** [comment]
> the story is very complicated :)
> 
> I would prefer using knobs for changing the maxWidth, that would be so much simpler. (usable only for dev-story tough)

Good idea, I'll change that.  

I think the dev-stories is enough for now, as it is a normal mui-feature. 
We could mention it in the docs under "Best Practices" though.

**Comment by jamesricky** [comment]
**Closed for #448** 

Pipelines can not be started in PR's from forks.

**Pull request closed without merging**
