### PR TITLE
feat(ci): move from travis to gitlab ci

### PR DESCRIPTION
**Pull request by kaufmo**
free travis-ci.org is end of life and travis-ci.com is only a paid service

### CODE REVIEW

**Review by nsams — APPROVED** [review]
cool!

...how does the integration into the github checks work?

**Comment by kaufmo** [comment]
> cool!
> 
> ...how does the integration into the github checks work?

I think that doesn't, its only connected via webhooks 🤷

**Comment by nsams** [comment]
but a failing lint is blocking, right?

**Comment by kaufmo** [comment]
> but a failing lint is blocking, right?

Yep that works fine 😘

**Review by dkarnutsch — APPROVED** [review]

**Review by rabengraph — APPROVED** [review]

**Pull request merged**
