### PR TITLE
StackLink Child Props

### PR DESCRIPTION
**Pull request by thomasdax98**
- Allow override of `StackLink` styling via theme
- Take props of `MuiLink` and `RouterLink` and pass them on

### CODE REVIEW

**Comment by nsams** [comment]
dev story, please :)

**Comment by thomasdax98** [comment]
@nsams Okay, I added the dev story

**Comment by nsams** [comment]
Idea (generally about StackLink):

Currently it uses mui Link, which brings it's own styling.

Wouldn't it make more sense to have no styling at all and behave more like a react-router Link and let the user of StackLink to decide on the required rendering?

**Comment by thomasdax98** [comment]
@nsams I actually think that it makes more sense for the StackLink to have the same styling as a normal MuiLink per default for consistency reasons. I think it might be a bit tedious to add custom styling every time when using the StackLink.

**Comment by nsams** [comment]
My point is, all those should be converted to a StackLink:
Bildschirmfoto vom 2021-08-17 13-32-55

Not a single one is currently a MuiLink, those are Buttons, MenuItems and whatnot.

**Comment by nsams** [comment]
See
https://material-ui.com/guides/composition/#routing-libraries, usage could be like:
```
<Button color="primary" component={StackLink} pageName="page2" payload="test">
    link with secondary color
</Button>
```

**Comment by thomasdax98** [comment]
> See
> https://material-ui.com/guides/composition/#routing-libraries, usage could be like:
> 
> ```
> <Button color="primary" component={StackLink} pageName="page2" payload="test">
>     link with secondary color
> </Button>
> ```

Ah okay, now I understand your point. That's a good idea 👍

**Comment by nsams** [comment]
:+1:

looks good!

tough I can't test in the story if the urls work correclty (as it's a Stroybook Router)

**Review by nsams — APPROVED** [review]

**Review by jamesricky — APPROVED** [review]

**Comment by nsams** [comment]
@thomasdax98 please extend the docs to show how usage with Button works (including link to mui docs)

**Comment by thomasdax98** [comment]
@nsams MR with updated Docs: https://github.com/vivid-planet/comet-admin/pull/481

**Pull request merged**
