### PR TITLE
Allow classes prop for all theme-able components

### PR DESCRIPTION
**Pull request by jamesricky**
This already worked for components using the `withStyles` hoc, now
components using the `useStyles` hook can also accept classes for
individual styling, without the theme.

_**Temporarily copy mergeClasses into admin-rte**
This commit should be reverted after the next alpha-release.
The `mergeClasses` function can currently not be imported from `@comet/admin`._

### CODE REVIEW

**Review by nsams — APPROVED** [review]
I don't fully understand the export issue though

**Comment by manuelblum** [comment]
good idea, i also thought about doing something like this.  👍

**Review by manuelblum — APPROVED** [review]

**Comment by rabengraph** [comment]
This technique allows to change the styling of components individually. Normally components have the styles defined in the theme. When you want to change the styling of a specific component, you can now pass additional classes to a component. Css-Rules of both classes are then merged.
Did I get this right?

Why do we need this? Is it too limiting to style components over the theme only?

**Comment by jamesricky** [comment]
> This technique allows to change the styling of components individually. Normally components have the styles defined in the theme. When you want to change the styling of a specific component, you can now pass additional classes to a component. Css-Rules of both classes are then merged.
> Did I get this right?

Yes, exactly 🙂

> Why do we need this? Is it too limiting to style components over the theme only?

There is no specific reason at the moment, but I think it should always be possible to customize individual components. For example, in some project we might one day need a second `Toolbar` below the first, where we might need to adjust the `z-index`, `top`, `height`, etc.

Also, since Material-UI uses the `withStyles` hoc internally, all material-ui components already support this and if our components also support this, it's more consistent.

**Review by kaufmo — APPROVED** [review]

**Review by rabengraph — APPROVED** [review]

**Pull request merged**
