### PR TITLE
Configure rte-colors using props instead of custom rte-key in theme

### PR DESCRIPTION
**Pull request by jamesricky**
Then `createMuiTheme` can be used from material-ui instead of from @comet/admin.

### CODE REVIEW

**Review by nsams — APPROVED** [review]

**Comment by nsams** [comment]
nice :+1:

**Comment by nsams** [comment]
could we have a codemod for this incompatible change?

**Comment by jamesricky** [comment]
> could we have a codemod for this incompatible change?

I can try 😄

**Review by rabengraph — APPROVED** [review]

**Comment by jamesricky** [comment]
> could we have a codemod for this incompatible change?

@nsams I made a codemod for the `createMuiTheme` import but couldn't figure out, how to move the `rte-colors` into the `props` of the theme-object.

**Review by nsams — APPROVED** [review]

**Review by kaufmo — APPROVED** [review]

**Pull request merged**
